### ISSUE TITLE
exceptions.TypeError raised when tried to use pyp2rpm

### ISSUE THREAD

**Issue by clime** [fedora-python/pyp2rpm#107]
Hello, I am getting the following exception on pretty much fresh f25 system when I try to use `pyp2rpm`(from master and also version 3.2.1-1 from Fedora):

    clime@coprbox ~/pyp2rpm $ ./mybin.py pyp2rpm
    Traceback (most recent call last):
      File "/home/clime/pyp2rpm/pyp2rpm/package_getters.py", line 31, in get_url
        release_urls = client.release_urls(name, version)
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
        verbose=self.__verbose
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1134, in request
        return self.single_request(host, handler, request_body, verbose)
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1150, in single_request
        return self.parse_response(resp)
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1322, in parse_response
        return u.close()
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 655, in close
        raise Fault(**self._stack[0])
    xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.TypeError'>:datetime.datetime(2017, 2, 7, 18, 0, 29, 834871) is not JSON serializable">

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "./mybin.py", line 5, in <module>
        main()
      File "/usr/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/clime/pyp2rpm/pyp2rpm/bin.py", line 177, in main
        converted = convertor.convert()
      File "/home/clime/pyp2rpm/pyp2rpm/convertor.py", line 96, in convert
        local_file = self.getter.get()
      File "/home/clime/pyp2rpm/pyp2rpm/package_getters.py", line 156, in get
        url = get_url(self.client, self.name, self.version, wheel, hashed_format=True)[0]
      File "/home/clime/pyp2rpm/pyp2rpm/package_getters.py", line 37, in get_url
        client), exc_info=True)
    TypeError: MissingUrlException does not take keyword arguments

**Comment by mcyprian** [comment]
This is [PyPI's XML-RPC API issue](https://github.com/pypa/pypi-legacy/issues/627). It seems to work for me now, It was probably fixed already.

**Comment by clime** [comment]
Right, it works now for me too. Thx
