### ISSUE TITLE
couldn't find requirements.txt

### ISSUE THREAD

**Issue by brianjmurrell** [fedora-python/pyp2rpm#151]
```
$ pyp2rpm google-assistant-sdk -s -d ~/tmp/gas -b 3 -v ''
INFO  Pyp2rpm initialized.
INFO  Using /home/brian/tmp/gas as directory to save source.
INFO  Downloaded package from PyPI: /home/brian/tmp/gas/google-assistant-sdk-0.3.3.tar.gz.
INFO  Getting metadata from setup.py using SetupPyMetadataExtractor.
INFO  Running extract_dist command using current interpreter.
ERROR  Subprocess failed, stdout: , stderr: Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    'samples': list(samples_requirements()),
  File "setup.py", line 32, in samples_requirements
    'requirements.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'googlesamples/assistant/grpc/requirements.txt'

ERROR  Error occured, trying alternative python interpreter.
ERROR  Subprocess failed, stdout: , stderr: Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    'samples': list(samples_requirements()),
  File "setup.py", line 32, in samples_requirements
    'requirements.txt')) as f:
IOError: [Errno 2] No such file or directory: 'googlesamples/assistant/grpc/requirements.txt'

Failed to extract data from setup.py script.
```
The contents of the tarball fetched from pypi:

```
$ tar tzvf ~/tmp/gas/google-assistant-sdk-0.3.3.tar.gz | grep setup-rw-r--r-- fleker/_guest    93 2017-07-19 20:51 google-assistant-sdk-0.3.3/setup.cfg
-rw-r--r-- fleker/_guest  2769 2017-07-19 20:29 google-assistant-sdk-0.3.3/setup.py
[brian@pc ~]$ tar tzvf ~/tmp/gas/google-assistant-sdk-0.3.3.tar.gz
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/
-rw-r--r-- fleker/_guest  1410 2017-07-19 20:49 google-assistant-sdk-0.3.3/CHANGELOG.rst
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/
-rw-r--r-- fleker/_guest     1 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/dependency_links.txt
-rw-r--r-- fleker/_guest   284 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/entry_points.txt
-rw-r--r-- fleker/_guest    38 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/namespace_packages.txt
-rw-r--r-- fleker/_guest  6340 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/PKG-INFO
-rw-r--r-- fleker/_guest   172 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/requires.txt
-rw-r--r-- fleker/_guest   768 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/SOURCES.txt
-rw-r--r-- fleker/_guest    14 2017-07-19 20:51 google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/top_level.txt
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/googlesamples/
-rw-r--r-- fleker/_guest   786 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/__init__.py
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/googlesamples/assistant/
-rw-r--r-- fleker/_guest   796 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/__init__.py
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/googlesamples/assistant/grpc/
-rw-r--r-- fleker/_guest   625 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/grpc/__init__.py
-rw-r--r-- fleker/_guest  2335 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/grpc/assistant_helpers.py
-rw-r--r-- fleker/_guest 13017 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/grpc/audio_helpers.py
-rw-r--r-- fleker/_guest 13515 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/grpc/pushtotalk.py
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/googlesamples/assistant/library/
-rw-r--r-- fleker/_guest     0 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/library/__init__.py
-rw-r--r-- fleker/_guest  2316 2017-07-19 19:41 google-assistant-sdk-0.3.3/googlesamples/assistant/library/hotword.py
-rw-r--r-- fleker/_guest 11361 2017-07-19 19:41 google-assistant-sdk-0.3.3/LICENSE
-rw-r--r-- fleker/_guest    67 2017-07-19 19:41 google-assistant-sdk-0.3.3/MANIFEST.in
-rw-r--r-- fleker/_guest  6340 2017-07-19 20:51 google-assistant-sdk-0.3.3/PKG-INFO
-rw-r--r-- fleker/_guest  4408 2017-07-19 19:41 google-assistant-sdk-0.3.3/README.rst
-rw-r--r-- fleker/_guest    93 2017-07-19 20:51 google-assistant-sdk-0.3.3/setup.cfg
-rw-r--r-- fleker/_guest  2769 2017-07-19 20:29 google-assistant-sdk-0.3.3/setup.py
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/tests/
drwxr-xr-x fleker/_guest     0 2017-07-19 20:51 google-assistant-sdk-0.3.3/tests/data/
-rw-r--r-- fleker/_guest 50288 2017-07-19 19:41 google-assistant-sdk-0.3.3/tests/data/whattimeisit.riff
-rw-r--r-- fleker/_guest  5112 2017-07-19 19:41 google-assistant-sdk-0.3.3/tests/test_audio_helpers.py
```

`google-assistant-sdk-0.3.3.tar.gz google-assistant-sdk-0.3.3/google_assistant_sdk.egg-info/requires.txt` has in it:

```
google-auth-oauthlib[tool]>=0.1.0

[samples]
google-assistant-grpc==0.0.2
google-auth-oauthlib==0.1.0
urllib3[secure]==1.21.1
sounddevice==0.3.7
click==6.7
tenacity==4.1.0
```

Is this some new/alternative way of doing what `requirements.txt` usually does?

**Comment by gordonmessmer** [comment]
This looks like a packaging bug in google-assistant-sdk.  "requirements.txt" exists in the Git repo, and is available if you clone and build the sdist from there.  However, the sdist will not include the "requirements.txt" file, so it can't be used to install the package.  Only the git repo and the built wheel archive are usable.
