### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

### ISSUE THREAD

**Issue by hroncok** [fedora-python/pyp2rpm#159]
```console
$ ./mybin.py -b3 -s sphinxcontrib_github_alt
INFO  Pyp2rpm initialized.
INFO  Using /home/churchyard/rpmbuild/SOURCES as directory to save source.
INFO  Downloaded package from PyPI: /home/churchyard/rpmbuild/SOURCES/sphinxcontrib_github_alt-1.0-py2.py3-none-any.whl.
INFO  Getting metadata from wheel using WheelMetadataExtractor.
Traceback (most recent call last):
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/archive.py", line 293, in json_wheel_metadata
    json_file = json.loads(self.get_content_of_file('metadata.json'))
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mybin.py", line 5, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/bin.py", line 211, in main
    converted = convertor.convert()
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/convertor.py", line 139, in convert
    data = self.metadata_extractor.extract_data(self.client)
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 94, in inner
    data = extraction_fce(self)
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 129, in inner
    data = extraction_fce(self)
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 261, in extract_data
    data.set_from(self.data_from_archive)
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 287, in data_from_archive
    archive_data['runtime_deps'] = self.runtime_deps
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 557, in runtime_deps
    run_requires = self.get_requires(['run_requires', 'meta_requires'])
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 549, in get_requires
    for requires in self.json_metadata.get(requires_name, []):
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/metadata_extractors.py", line 538, in json_metadata
    self._json_metadata = self.archive.json_wheel_metadata
  File "/home/churchyard/Dokumenty/RedHat/pyp2rpm/pyp2rpm/archive.py", line 295, in json_wheel_metadata
    json_file = json.loads(self.get_content_of_file('pydist.json'))
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
```

This only has whl, but the error is cryptic.

**Comment by irushchyshyn** [comment]
For wheel packages we rely on the existence of either `metadata.json` or `pydist.json` file to extract metadata from.
As `sphinxcontrib_github_alt` uses wheel version 1.0, it does not have those files, it's .dist-info directory includes METADATA, WHEEL, and RECORD, where METADATA file is of the same format as PKG-INFO files. pyp2rpm does not have the functionality to parse those afaik.
To make this work we should add support for extracting info from METADATA files.

**Comment by hroncok** [comment]
I would feel satisfied with a decent error message that explains why this doesn't work.
