### ISSUE TITLE
Fails to build the spec file for the pip module pkginfo

### ISSUE THREAD

**Issue by tuxmaster5000** [fedora-python/pyp2rpm#176]
Call  pyp2rpm -o epel7 -s pkginfo fails with:

> Traceback (most recent call last):
>   File "/home/foo/.local/bin/pyp2rpm", line 11, in <module>
>     sys.exit(main())
>   File "/home/foo/.local/lib/python3.4/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/foo/.local/lib/python3.4/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/foo/.local/lib/python3.4/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/foo/.local/lib/python3.4/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/bin.py", line 210, in main
>     converted = convertor.convert()
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/convertor.py", line 143, in convert
>     data = self.metadata_extractor.extract_data(self.client)
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/metadata_extractors.py", line 94, in inner
>     data = extraction_fce(self)
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/metadata_extractors.py", line 129, in inner
>     data = extraction_fce(self)
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/metadata_extractors.py", line 261, in extract_data
>     data.set_from(self.data_from_archive)
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/metadata_extractors.py", line 517, in data_from_archive
>     archive_data = super(SetupPyMetadataExtractor, self).data_from_archive
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/metadata_extractors.py", line 292, in data_from_archive
>     archive_data['scripts'] = self.scripts
>   File "/home/foo/.local/lib/python3.4/site-packages/pyp2rpm/metadata_extractors.py", line 430, in scripts
>     equal_sign = script.find('=')
> AttributeError: 'list' object has no attribute 'find'

**Comment by tuxmaster5000** [comment]
Using it for other packages will work.

**Comment by hroncok** [comment]
pkginfo has:

```python
    entry_points={
      'console_scripts': [
        ['pkginfo = pkginfo.commandline:main']
      ]
    },
```

Yet [the docs](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) mention it like this:

```python
    entry_points = {
        'console_scripts': ['funniest-joke=funniest.command_line:main'],
    }
```

I think this is a bug in pkginfo having 2 nested lists instead of one flat list.

Or is this supposed to work?

**Comment by tuxmaster5000** [comment]
I have open an bug [report](https://bugs.launchpad.net/pkginfo/+bug/1810734) at the developer of pkginfo.
So I hope the people there can help us.
