### ISSUE TITLE
New installation doesn't work.

### ISSUE THREAD

**Issue by nat-n** [fedora-python/pyp2rpm#237]
I did:

```bash
pip install pyp2rpm
pyp2rpm -h
```

The result was:
```
Traceback (most recent call last):
  File "/.../virtualenvs/ziEwgQLP-py3.6/bin/pyp2rpm", line 5, in <module>
    from pyp2rpm.bin import main
  File "/.../virtualenvs/ziEwgQLP-py3.6/lib/python3.6/site-packages/pyp2rpm/bin.py", line 5, in <module>
    from pyp2rpm.convertor import Convertor
  File "/.../virtualenvs/ziEwgQLP-py3.6/lib/python3.6/site-packages/pyp2rpm/convertor.py", line 28, in <module>
    from pyp2rpm import filters
  File "/.../virtualenvs/ziEwgQLP-py3.6/lib/python3.6/site-packages/pyp2rpm/filters.py", line 1, in <module>
    from pyp2rpm import settings
  File "/.../virtualenvs/ziEwgQLP-py3.6/lib/python3.6/site-packages/pyp2rpm/settings.py", line 15, in <module>
    DEFAULT_PKG_SAVE_PATH = utils.get_default_save_path()
  File "/.../virtualenvs/ziEwgQLP-py3.6/lib/python3.6/site-packages/pyp2rpm/utils.py", line 169, in get_default_save_path
    save_path = rpm.expandMacro(macro)
AttributeError: module 'rpm' has no attribute 'expandMacro'
```

I installed pyp2rpm-3.3.4-py3-none-any.whl on Python 3.6.8, [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)] on darwin.

**Comment by gordonmessmer** [comment]
I don't have a copy of OS X handy, but I suspect that the "rpm" module isn't the one that's needed.  

Can you try this in a shell?

```
$ python3
>>> import rpm
>>> print(rpm.__doc__)
RPM Module

This module enables you to manipulate rpms and the rpm database.
...
```

You should see those three lines preceding a description of managing the rpm database.

I'd suggest building a docker container based on Fedora in order to run pyp2rpm on OS X.

**Comment by nat-n** [comment]
Indeed, my virtual env seemed to be pulling in a local directory (with no python code in it) at ./rpm as a namespace package so I was getting that :/

My bad. Thanks for the response. I'll close.
