### ISSUE TITLE
Crash when using prerelease option

### ISSUE THREAD

**Issue by papoteur-mga** [fedora-python/pyp2rpm#285]
```
pyp2rpm --prerelease azure-common
Traceback (most recent call last):
  File "/usr/bin/pyp2rpm", line 33, in <module>
    sys.exit(load_entry_point('pyp2rpm==3.3.5', 'console_scripts', 'pyp2rpm')())
  File "/home/yves/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/yves/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/yves/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yves/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyp2rpm/bin.py", line 215, in main
    converted = convertor.convert()
  File "/usr/lib/python3.8/site-packages/pyp2rpm/convertor.py", line 135, in convert
    local_file = self.getter.get()
  File "/usr/lib/python3.8/site-packages/pyp2rpm/convertor.py", line 195, in getter
    self._getter = package_getters.PypiDownloader(
  File "/usr/lib/python3.8/site-packages/pyp2rpm/package_getters.py", line 142, in __init__
    self.version = version or self.versions[0]
TypeError: 'dict_keys' object is not subscriptable
```
Note that the package doesn't exist on pypi.org.
```
pyp2rpm azure-common
azure-common package has no sources on PyPI, Please ask the maintainer to upload sources.
```
Version: pyp2rpm-3.3.5-1.mga8

**Comment by papoteur-mga** [comment]
And the assumption that there is no source files is false.
https://pypi.org/project/azure-common/#files
