### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by clime** [fedora-python/pyp2rpm#29]
```
clime@coprbox /var/log/copr $ pyp2rpm motionpaint --srpm -d /tmp/tmpzwwzaj -b 3
INFO  Pyp2rpm initialized.
INFO  Using /tmp/tmpzwwzaj as directory to save source.
Traceback (most recent call last):
  File "/usr/bin/pyp2rpm", line 9, in <module>
    load_entry_point('pyp2rpm==2.0.0', 'console_scripts', 'pyp2rpm')()
  File "/usr/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/pyp2rpm/bin.py", line 99, in main
    converted = convertor.convert()
  File "/usr/lib/python3.4/site-packages/pyp2rpm/convertor.py", line 63, in convert
    local_file = self.getter.get()
  File "/usr/lib/python3.4/site-packages/pyp2rpm/package_getters.py", line 85, in get
    save_file = '{0}/{1}'.format(self.save_dir, self.url.split('/')[-1])
  File "/usr/lib/python3.4/site-packages/pyp2rpm/package_getters.py", line 76, in url
    return urls[0]['url']
IndexError: list index out of range
```

Probably, it cannot get url of the package "motionpaint", that I have just recently added into PyPI.

**Comment by clime** [comment]
It is because I haven't uploaded any tar.gz file to PyPI :-). After actually uploading one, it started to work.
