### ISSUE TITLE
pyp2rpm crash when numpy is a require 

### ISSUE THREAD

**Issue by jehane** [fedora-python/pyp2rpm#82]
I'm trying to use pyp2rpm on a pypi module who need numpy to compile and the program is crashing. 
Here is the stacktrace : 

 pyp2rpm nitime  
Traceback (most recent call last):
  File "/usr/bin/pyp2rpm", line 9, in <module>
    load_entry_point('pyp2rpm==3.1.3', 'console_scripts', 'pyp2rpm')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pyp2rpm/bin.py", line 99, in main
    converted = convertor.convert()
  File "/usr/lib/python3.5/site-packages/pyp2rpm/convertor.py", line 83, in convert
    data = self.metadata_extractor.extract_data(self.client)
  File "/usr/lib/python3.5/site-packages/pyp2rpm/convertor.py", line 191, in metadata_extractor
    self.base_python_version)
  File "/usr/lib/python3.5/site-packages/pyp2rpm/metadata_extractors.py", line 412, in **init**
    extract_distribution.run_setup(setup_py, 'bdist_rpm')
  File "/usr/lib/python3.5/site-packages/pyp2rpm/extract_distribution.py", line 86, in run_setup
    runpy.run_module(filename, run_name='**main**', alter_sys=True)
  File "/usr/lib64/python3.5/runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/tmp912ptmn8/nitime-0.6/setup.py", line 17, in <module>
  File "<string>", line 2, in <module>
  File "/tmp/tmp912ptmn8/nitime-0.6/nitime/__init__.py", line 26, in <module>
  File "/tmp/tmp912ptmn8/nitime-0.6/nitime/algorithms/**init**.py", line 55, in <module>
  File "/tmp/tmp912ptmn8/nitime-0.6/nitime/algorithms/spectral.py", line 10, in <module>
ImportError: No module named 'numpy'

**Comment by mcyprian** [comment]
This was bug in setup.py script of nitime package https://github.com/nipy/nitime/issues/141.
